services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: Chacal_bot_PURE
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./strategies:/freqtrade/user_data/strategies"
      - "c:/ai_trading_agent/PROYECTO_CHACAL_PULSE/user_data/data:/freqtrade/user_data/data"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    environment:
      - FREQTRADE_WORKERS=1
    command: >
      hyperopt
      --strategy ChacalPure_Adaptativo
      --config /freqtrade/user_data/config_pure.json
      --hyperopt-loss OnlyProfitHyperOptLoss
      --epochs 100
      --spaces buy sell
      --timerange 20250101-
      --fee 0.001
      --enable-position-stacking
